### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Weesli** [Weesli/RClaim#1]
Plugin is released!!

**Comment by ThePowerrTR** [comment]
Hey merhaba Weesli. Eklenti içeriğinde gördüğüm kadarı ile claim alırken bölgeler yün olarak gösteriliyor alacağımız zaman oraya bir tarım bölgesi eklermisiniz ?

İÇERİK OLARAK

- Tarım bölgesinde [Chunk'ında] büyüyen tarım ürünleri 2x veya %35 gibi bir özellikle daha hızlı büyüsün.
- Tarım bölgesi x miktarda alınabilinsin. [ Sınırlı sayıda]


Ek olarak Koruma alanı, Koruma Bölgesi vb. Bölgeler eklenebilir. 

İÇERİK OLARAK

- Korum bölgesi ilk alındığı zaman o Şekilde kayıt edilir ve Koruma bölgesini oyuncular belli bir ücret ike Bozulduğunda veya kırıldığında tekrardan eski şekline geri getirilebilsin.

veya bu içerik için

- Alındığı şekilde kayıt değil. Diğer oyuncular eğer o claimin dışını bozup trollerlerse. Trollenen claim alınır [KORUMA BÖLGESİ] içerisindeki belirli bloklar silinir.

Örnek Olarak
-SU
-KIRIKTAŞ
-ODUN
-BUZ ve benzeri bir çok block eklenebilir.

**Comment by Weesli** [comment]
> * Korum bölgesi ilk alındığı zaman o Şekilde kayıt edilir ve Koruma bölgesini oyuncular belli bir ücret ike Bozulduğunda veya kırıldığında tekrardan eski şekline geri getirilebilsin.

Bi

**Comment by Weesli** [comment]
> Hey merhaba Weesli. Eklenti içeriğinde gördüğüm kadarı ile claim alırken bölgeler yün olarak gösteriliyor alacağımız zaman oraya bir tarım bölgesi eklermisiniz ?
> 
> İÇERİK OLARAK
> 
> * Tarım bölgesinde [Chunk'ında] büyüyen tarım ürünleri 2x veya %35 gibi bir özellikle daha hızlı büyüsün.
> * Tarım bölgesi x miktarda alınabilinsin. [ Sınırlı sayıda]
> 
> Ek olarak Koruma alanı, Koruma Bölgesi vb. Bölgeler eklenebilir.
> 
> İÇERİK OLARAK
> 
> * Korum bölgesi ilk alındığı zaman o Şekilde kayıt edilir ve Koruma bölgesini oyuncular belli bir ücret ike Bozulduğunda veya kırıldığında tekrardan eski şekline geri getirilebilsin.
> 
> veya bu içerik için
> 
> * Alındığı şekilde kayıt değil. Diğer oyuncular eğer o claimin dışını bozup trollerlerse. Trollenen claim alınır [KORUMA BÖLGESİ] içerisindeki belirli bloklar silinir.
> 
> Örnek Olarak -SU -KIRIKTAŞ -ODUN -BUZ ve benzeri bir çok block eklenebilir.

İlk örnek olabilir ancak ikinci olarak pek mantıklı değil
