### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by iamBinhz** [Weesli/RClaim#2]
Hello, the plugin has only been released for a few days, but I've already noticed that it's a great plugin compared to others with the same theme. However, there are a few features that I would like the developer to add:

Limiting claims to certain worlds: Servers often have multiple worlds, so this is a feature that cannot be overlooked.
Increasing the cost of claiming additional land: Currently, when you already own a claim and want to own another, the cost remains the same as the initial price. I feel that the cost should increase when claiming additional regions. For example, the price could increase by 1.1x when claiming one more chunk, 1.2x for two chunks, etc.
These are my suggestions. Overall, it is still an excellent plugin. I hope the developers will continue to release new updates with more features.

Best regards!

**Comment by Weesli** [comment]
> Hello, the plugin has only been released for a few days, but I've already noticed that it's a great plugin compared to others with the same theme. However, there are a few features that I would like the developer to add:
> 
> Limiting claims to certain worlds: Servers often have multiple worlds, so this is a feature that cannot be overlooked.
> Increasing the cost of claiming additional land: Currently, when you already own a claim and want to own another, the cost remains the same as the initial price. I feel that the cost should increase when claiming additional regions. For example, the price could increase by 1.1x when claiming one more chunk, 1.2x for two chunks, etc.
> These are my suggestions. Overall, it is still an excellent plugin. I hope the developers will continue to release new updates with more features.
> 
> Best regards!

Greetings, 

First of all, thank you, world limitation is a very nice option. We can add a price increase according to the number of requests, of course, some people may not be satisfied with this, so I am thinking of making a setting that can be turned off and on. 


Thank you 🙏

**Comment by iamBinhz** [comment]
> > Hello, the plugin has only been released for a few days, but I've already noticed that it's a great plugin compared to others with the same theme. However, there are a few features that I would like the developer to add:
> > Limiting claims to certain worlds: Servers often have multiple worlds, so this is a feature that cannot be overlooked.
> > Increasing the cost of claiming additional land: Currently, when you already own a claim and want to own another, the cost remains the same as the initial price. I feel that the cost should increase when claiming additional regions. For example, the price could increase by 1.1x when claiming one more chunk, 1.2x for two chunks, etc.
> > These are my suggestions. Overall, it is still an excellent plugin. I hope the developers will continue to release new updates with more features.
> > Best regards!
> 
> Greetings,
> 
> First of all, thank you, world limitation is a very nice option. We can add a price increase according to the number of requests, of course, some people may not be satisfied with this, so I am thinking of making a setting that can be turned off and on.
> 
> Thank you 🙏

I must thank you for an amazing plugin ! By the way, did you consider adding some placeholder?

**Comment by Weesli** [comment]
> > > Hello, the plugin has only been released for a few days, but I've already noticed that it's a great plugin compared to others with the same theme. However, there are a few features that I would like the developer to add:
> > > Limiting claims to certain worlds: Servers often have multiple worlds, so this is a feature that cannot be overlooked.
> > > Increasing the cost of claiming additional land: Currently, when you already own a claim and want to own another, the cost remains the same as the initial price. I feel that the cost should increase when claiming additional regions. For example, the price could increase by 1.1x when claiming one more chunk, 1.2x for two chunks, etc.
> > > These are my suggestions. Overall, it is still an excellent plugin. I hope the developers will continue to release new updates with more features.
> > > Best regards!
> > 
> > 
> > Greetings,
> > First of all, thank you, world limitation is a very nice option. We can add a price increase according to the number of requests, of course, some people may not be satisfied with this, so I am thinking of making a setting that can be turned off and on.
> > Thank you 🙏
> 
> I must thank you for an amazing plugin ! By the way, did you consider adding some placeholder?

Like what?

**Comment by iamBinhz** [comment]
> > > > Hello, the plugin has only been released for a few days, but I've already noticed that it's a great plugin compared to others with the same theme. However, there are a few features that I would like the developer to add:
> > > > Limiting claims to certain worlds: Servers often have multiple worlds, so this is a feature that cannot be overlooked.
> > > > Increasing the cost of claiming additional land: Currently, when you already own a claim and want to own another, the cost remains the same as the initial price. I feel that the cost should increase when claiming additional regions. For example, the price could increase by 1.1x when claiming one more chunk, 1.2x for two chunks, etc.
> > > > These are my suggestions. Overall, it is still an excellent plugin. I hope the developers will continue to release new updates with more features.
> > > > Best regards!
> > > 
> > > 
> > > Greetings,
> > > First of all, thank you, world limitation is a very nice option. We can add a price increase according to the number of requests, of course, some people may not be satisfied with this, so I am thinking of making a setting that can be turned off and on.
> > > Thank you 🙏
> > 
> > 
> > I must thank you for an amazing plugin ! By the way, did you consider adding some placeholder?
> 
> Like what?

like placeholder show the owner of the claim, show how many claims u have, etc
