### ISSUE TITLE
[1.20.1-Spigot] | TNT explosion problem

### ISSUE THREAD

**Issue by TeQTabanca** [Weesli/RClaim#7]
Although the TNT explosion feature is disabled by default in the claim zone, if I put a TNT block 1 block away from the claim zone and explode it, it will explode in the blocks in the claim zone.

https://github.com/user-attachments/assets/7a22b980-0d88-4edb-9ff8-1e28f36433f7

**Comment by Weesli** [comment]
I will provide a study on this problem :)
